// App-level build.gradle

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
}

android {
    namespace "com.meldcx.appschedule"
    compileSdk 35

    defaultConfig {
        applicationId "com.meldcx.appschedule"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation libs.kotlin.stdlib
    implementation libs.kotlinx.coroutines.android

    implementation libs.androidx.core.ktx.v1120
    implementation libs.androidx.appcompat.v161
    implementation libs.androidx.recyclerview.v131

    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.ktx

    implementation libs.androidx.cardview
    implementation libs.material

    // Room
    implementation libs.androidx.room.runtime
    implementation libs.room.ktx
    ksp libs.androidx.room.compiler

    implementation libs.lottie
    implementation libs.gson
    implementation 'com.github.Armen101:AudioRecordView:1.0.5'
    implementation "androidx.work:work-runtime-ktx:2.9.0"
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
}

